spring.application.name=reservation
spring.jackson.time-zone=Asia/Seoul
spring.jpa.hibernate.ddl-auto=create-drop

# Open-In-View 경고 제거 및 데이터베이스 커넥션 최적화
spring.jpa.open-in-view=false

# H2 웹 콘솔 활성화 및 주소 고정
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa

# JPA 스키마 생성 후 data.sql 적용
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always